[package]
name = "ultimate-fate-history"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "ultimate_fate_history"

[dependencies]
ultimate-fate-content = { path = "../game_content" }
ultimate-fate-core = { path = "../game_core" }
ultimate-fate-world-atlas = { path = "../world_atlas" }
